name: Build Cluely Installer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- PASO AÑADIDO ---
      # Forzamos el uso de Python 3.11, que es compatible con node-gyp
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install windows-build-tools
        run: npm install -g windows-build-tools

      - name: Install dependencies
        shell: cmd
        run: npm install

      - name: Build Electron App
        run: |
          npm run build || echo "No build script"
          npx electron-builder --win --x64

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Cluely-Installer
          # Asegúrate de que la ruta sea correcta, 'dist' es común para electron-builder
          path: dist/*.exe