name: Electron Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: npm ci

      - name: Install ffi-napi without scripts and patch
        shell: pwsh
        run: |
          npm install ffi-napi --no-save --ignore-scripts
          cd node_modules/ffi-napi/deps/libffi
          $file = 'libffi.gyp'
          $content = Get-Content $file -Raw
          $content = $content -replace "\'call\',\s*\'preprocess_asm.cmd\'", "\'preprocess_asm.cmd\'"
          Set-Content $file $content
          cd ../../../..
          npx node-gyp rebuild -C node_modules/ffi-napi

      - name: Build Electron App
        run: npm run dist

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Llamada-Proto-Installer
          path: dist/*.exe
